# Generated by Django 3.2 on 2022-10-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20221020_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='updated_at',
        ),
    ]
